### ISSUE TITLE
Ladda bilderna som ligger LS på shoppingcart

### ISSUE THREAD

**Issue by Cajolina** [Cajolina/TechStore8#49]
Shoppingcart js : 
Skapa element (h2,p,img,p,button) och få ut på sidan. Koppla elementen till local storage så det visar på sidan vad vi lagt i shoppingcart (LS)

+
Siffran vid kundvagnen måste fixas så den syns när man har reloadat.

**Comment by Cajolina** [comment]
Räkna längden på produkterna vi har i shoppingcarten när vi har en key i LS

**Comment by ForumMannen** [comment]
Closing this! Nice work!
